apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  USERHOST:    YXV0aC1kYi1zZXJ2aWNlLWxiLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
  USERUSER:    cm9vdA==
  USERPASS:    eW9uMTMz
  USERDB:      dXNlcnM=
  USDERPORT:   MzMwNg==
  GUITARHOST:  Z3VpdGFyLWRiLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  GUITARUSER:  cm9vdA==
  GUITARPASS:  eW9uMTMz
  GUITARDB:    cHJvZHVjdF9jYXRhbG9n
  GUITARPORT:  MzMwNg==












